name = "sidan-lab/aiken-pbl-hk-101"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'sidan-lab/aiken-pbl-hk-101'"

[repository]
user = "sidan-lab"
project = "aiken-pbl-hk-101"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"
