name = "sidan-lab/aiken-pbl-hk"
version = "0.0.0"
compiler = "v1.1.1"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'sidan-lab/aiken-pbl-hk'"

[repository]
user = "sidan-lab"
project = "aiken-pbl-hk-101"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.0-beta"
source = "github"

[config]
